CREATE DATABASE IF NOT EXISTS lemp_stack;
USE lemp_stack;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
CREATE TABLE IF NOT EXISTS lemp_stack.test (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO lemp_stack.test (name) VALUES ('John'), ('Doe');
COMMIT;